---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maps.k8s.imgswap.io
  resources:
  - swapmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maps.k8s.imgswap.io
  resources:
  - swapmaps/finalizers
  verbs:
  - update
- apiGroups:
  - maps.k8s.imgswap.io
  resources:
  - swapmaps/status
  verbs:
  - get
  - patch
  - update
