# permissions for end users to view swapmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: swapmap-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: imgswap
    app.kubernetes.io/part-of: imgswap
    app.kubernetes.io/managed-by: kustomize
  name: swapmap-viewer-role
rules:
- apiGroups:
  - maps.k8s.imgswap.io
  resources:
  - swapmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maps.k8s.imgswap.io
  resources:
  - swapmaps/status
  verbs:
  - get
